name : Build and package ROBERTA-SEQUENCING TO DOCKERHUB

on:
  #triggers the workflow on pull or push  request events for the main branch
  
  push:
    branches: [ main ]
  #allow to run this worflow mannually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on : ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Authenticate wit azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    #- name: Install Azure ML CLI extension
    #  run: az extension add -n ml

    
    - name: set auto-install of extensions
      run: az config set extension.use_dynamic_install=yes_without_prompt
    #- name: attach workspace
    #  run: az ml folder attach -w Preactical_ml_book -g evanskipsang21-rg
    #- name: retrieve the model
      #run: az ml model download -t "." --model-id "roberta--seqence:1"
    - name: Download the model
      run: az ml model download --name roberta-seqence --version 1 --download-path "." -w "Preactical_ml_book" -g "evanskipsang21-rg"

    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_HUB_REGISTRY}}
        


    - name: build flask-app container AND PUSH TO REGISTRY
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ghcr.io/Evans-tats/flask-roberta:latest
